name: custom_date_range_picker
description: A Flutter package for both Android and iOS that provides a customizable date range picker with beautiful UI and smooth animations.
version: 1.2.0
homepage: https://github.com/El-Mazouzi/custom_date_range_picker
repository: https://github.com/El-Mazouzi/custom_date_range_picker
issue_tracker: https://github.com/El-Mazouzi/custom_date_range_picker/issues
documentation: https://github.com/El-Mazouzi/custom_date_range_picker#readme

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:

topics:
  - date-picker
  - date-range
  - calendar
  - ui
  - widget
